trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Build_Scan
  displayName: Build + SonarCloud
  container: maven:3.8.1-openjdk-17-slim

  steps:
  - checkout: self
    fetchDepth: 0

  - script: |
      mvn -B -f pom.xml clean verify \
        org.sonarsource.scanner.maven:sonar-maven-plugin:3.10.0.2594:sonar \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.organization=xabiere-designs \
        -Dsonar.projectKey=Xabiere-Designs_Azure-DevOps \
        -Dsonar.token=$(SONAR_TOKEN) \
        -Dsonar.branch.name=$(Build.SourceBranchName)
    displayName: Build + Test + Sonar (Maven)
