trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: SECURE_TOKENS   # contains SNYK_TOKEN (secret)

steps:
- script: |
    mvn -B \
      io.snyk:snyk-maven-plugin:2.0.0:test \
      -Dsnyk.organization="xabiere-designs" \
      -DfailOnSeverity=high
  displayName: "Snyk SCA scan (Maven)"
  env:
    SNYK_TOKEN: $(SNYK_TOKEN)   # provided by your variable group
